---
title: "Class Schedule"
format:
  html:
    toc: true
    page-layout: full
---

Spring 2026 class schedule.

## Schedule

+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| Week   | Day   | Date   | Topic                                                                             | Readings/Assignments |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 1      | M     | Jan 12 | Introduction to Course                                                            |                      |
|        |       |        |                                                                                   |                      |
|        |       |        | Icebreaker                                                                        |                      |
|        |       |        |                                                                                   |                      |
|        |       |        | [Syllabus](syllabus/)                                                             |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 1      | W     | Jan 14 | [Module 1: The Environment and Sustainability](../module-1/)                      |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 2      | M     | Jan 19 | No Classes (Martin Luther King, Jr. Holiday)                                      |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 2      | W     | Jan 21 | Module 1 continued                                                                |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 3      | M     | Jan 26 | [Module 2: Science, Matter, Energy, and Systems](../module-2/)                    |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 3      | W     | Jan 28 | Module 2 continued                                                                |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 4      | M     | Feb 2  | Module 2 continued                                                                |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 4      | W     | Feb 4  | Activity 1: in-class activity                                                     |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 5      | M     | Feb 9  | [Module 3: Ecosystems: What are they and how do they work?](../module-3/)         |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 5      | W     | Feb 11 | Module 3 continued                                                                | Activity 1 Due       |
|        |       |        |                                                                                   |                      |
|        |       |        | [Module 4: Human Population and Urbanization](../module-4/)                       |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 6      | M     | Feb 16 | No Class (Non-Instructional Day)                                                  |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 6      | W     | Feb 18 | **Exam 1: Modules 1–3**                                                           |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 7      | M     | Feb 23 | Module 4 continued                                                                |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 7      | W     | Feb 25 | No class (instructor at conference)                                               |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 8      | M     | Mar 2  | [Module 5: Climate and Biodiversity: Saving Species and Ecosystems](../module-5/) |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 8      | W     | Mar 4  | Module 5 continued                                                                | Activity 2 Due       |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 9      | M     | Mar 9  | No Class (Spring Break)                                                           |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 9      | W     | Mar 11 | No Class (Spring Break)                                                           |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 10     | M     | Mar 16 | Module 5 continued                                                                |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 10     | W     | Mar 18 | [Module 6: Food Production and the Environment](../module-6/)                     |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 11     | M     | Mar 23 | Module 6 continued                                                                |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 11     | W     | Mar 25 | **Exam 2: Modules 4–5**                                                           |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 12     | M     | Mar 30 | [Module 7: Natural Resources](../module-7/)                                       |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 12     | W     | Apr 1  | Module 7 continued                                                                |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 13     | M     | Apr 6  | No Class (instructor gone)                                                        |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 13     | W     | Apr 8  | Module 7 continued                                                                | Activity 3 Due       |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 14     | M     | Apr 13 | [Module 8: Air Pollution and Climate Change](../module-8/)                        |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 14     | W     | Apr 15 | **Exam 3: Modules 6–7**                                                           |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 15     | M     | Apr 20 | Module 8 continued                                                                |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 15     | W     | Apr 22 | Module 8 continued                                                                |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 16     | M     | Apr 27 | [Module 9 Environmental Waste and Human Health](../module-9/)                     | Activity 4 Due       |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| 16     | W     | Apr 29 | Module 9 continued                                                                |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
| Finals | H     | May 7  | **FINAL EXAM\                                                                     |                      |
|        |       |        | Thursday, May 7\                                                                  |                      |
|        |       |        | 9:45-11:45 am**                                                                   |                      |
+--------+-------+--------+-----------------------------------------------------------------------------------+----------------------+
